services:
  client:
    image: wasted-vue-client
    container_name: wasted-client
    ports:
      - '5173:80/tcp'
    depends_on:
      - server
  server:
    image: wasted-server
    container_name: wasted-server
    env_file:
      - ./environment/.env
    ports:
      - '8080:8080/tcp'
    volumes:
      - ./environment/config.json:/app/config.json
      - ./environment/database.json:/app/database.json
