name: Build
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Linting and checking format
              run: |
                  npm run lint
                  npm run format:check
            - name: Build projects
              run: npm run build
            - name: Test projects
              run: npm run test
